### ISSUE TITLE
:action argument target is always undefined

### ISSUE THREAD

**Issue by maczor** [smellyshovel/vue-custom-context-menu#11]

**Comment by smellyshovel** [comment]
First of all, thank you for your interest to my plugin.

Do you use the last (3d) version?

**Comment by smellyshovel** [comment]
Quick update: I can see and reproduce the issue, this is actually a bug caused by my inattention. I'll fix it in around 5-10 minutes and'll let you know when it's done.

**Comment by smellyshovel** [comment]
Done! Make sure to update to v3.0.1. And thank you again for opening the issue!
